// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgoxnvfjmggahnrrdhqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnb3hudmZqbWdnYWhucnJkaHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjgzOTQsImV4cCI6MjA2MTEwNDM5NH0.2nLcToS4s8SoMXHKm57Qxcdlq2R2TctinNGkaa6w_Dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);